### ISSUE TITLE
missing relevant citation

### ISSUE THREAD

**Issue by Howuhh** [FutureAGI/Xenoverse#1]
Hi! My name is Alexander Nikulin, I am a researcher at AIRI working on
offline rl / meta-rl ([howuhh.github.io](http://howuhh.github.io/)).

We've been working on an environment and benchmark for meta-RL and
in-context RL called [XLand-MiniGrid](https://github.com/corl-team/xland-minigrid) for quite some time now. We would
be glad if you would include mention in related work, as it addresses many
of the problems that you, as well as we, have noted.

https://arxiv.org/abs/2312.12044

Thanks!

**Comment by WorldEditors** [comment]
Sorry for missing the relevant citations, we'll add it to reference in our next version.

**Comment by Howuhh** [comment]
Thank you very much!
