### ISSUE TITLE
where is l3c?

### ISSUE THREAD

**Issue by BackMountainDevil** [FutureAGI/Xenoverse#2]
```bash
.
├── l3c
│   ├── bandits
│   ├── __init__.py
│   ├── mazeworld
│   └── metalang
├── LICENSE
├── README.md
├── requirements.txt
└── setup.py
```

there are just three env in l3c dir

**Comment by WorldEditors** [comment]
Sorry for not quite get your problem. l3c is the name of this repo, which is composed of different environments. Currently we have three environments "MetaLanguage", "Maze World" and "Bandits"

**Comment by BackMountainDevil** [comment]
got it. My apology. I thought it is an in context rl alg.

**Comment by WorldEditors** [comment]
We implement the baseline solutions in  
https://github.com/FutureAGI/L3C_Baselines
